services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: egocentric_vision
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # pg_isready に -q (quiet) を追加して成功時/失敗時の出力を抑制
      test: ["CMD-SHELL", "pg_isready -U user -d egocentric_vision -q"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s  # 起動後、最初の10秒間は失敗しても異常と見なさない猶予期間

  record-service:
    build:
      context: ./src/record
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      RECORD_DATABASE__URL: "postgres://user:password@postgres:5432/egocentric_vision"
      RECORD_RECORDING_DIRECTORY: "/var/data/recordings"
      GST_DEBUG_DUMP_DOT_DIR: "/tmp"
      GST_DEBUG: "3"
    volumes:
      - ./config:/app/config:ro
      - ./recordings_data:/var/data/recordings
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      VITE_API_BASE_URL: "http://localhost:8080"
    depends_on:
      - record-service
    restart: unless-stopped

volumes:
  postgres_data:
  # recordings_data: