# Record service configuration

# Directory where recordings will be saved
recording_directory: /var/data/recordings

# Database configuration
database:
  # PostgreSQL connection URL
  url: "postgres://user:password@postgres:5432/egocentric_vision"

# Stream configuration
stream:
  # Default RTSP URL (optional)
  default_rtsp_url: "rtsp://192.168.0.18:8554/cam1"

# Server configuration
server:
  host: "0.0.0.0"
  port: 3000